//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOmega.DAL.Firebird
{
    using System;
    using System.Collections.Generic;
    
    public partial class R3_CONTACT_PHONES
    {
        public int ID { get; set; }
        public string NUMBER { get; set; }
        public int TYPE_ID { get; set; }
        public int CONTACT_ID { get; set; }
        public int PERSON_ID { get; set; }
    
        public virtual R3_CONTACTS R3_CONTACTS { get; set; }
    }
}
